"""Initial migration

Revision ID: 03b57d333b5c
Revises: 
Create Date: 2025-01-29 11:46:39.436201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b57d333b5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('watchlists')
    op.drop_table('cryptocurrencies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrencies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('market_price', sa.NUMERIC(precision=20, scale=8), nullable=False),
    sa.Column('market_cap', sa.NUMERIC(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cryptocurrency_id', sa.INTEGER(), nullable=False),
    sa.Column('alert_price', sa.NUMERIC(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], name='fk_watchlists_cryptocurrency_id_cryptocurrencies'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cryptocurrency_id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=20, scale=8), nullable=False),
    sa.Column('recorded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], name='fk_price_history_cryptocurrency_id_cryptocurrencies'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
