"""Initial migration

Revision ID: d1456c8a12fd
Revises: 03b57d333b5c
Create Date: 2025-01-29 12:35:39.636235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1456c8a12fd'
down_revision = '03b57d333b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trending_cryptocurrencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cryptocurrency_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], name=op.f('fk_trending_cryptocurrencies_cryptocurrency_id_cryptocurrencies')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_Cryptocurrencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('alert_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptocurrencies.id'], name=op.f('fk_user_Cryptocurrencies_crypto_id_cryptocurrencies')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_Cryptocurrencies_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('watchlists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cryptocurrency_id', sa.INTEGER(), nullable=False),
    sa.Column('alert_price', sa.NUMERIC(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], name='fk_watchlists_cryptocurrency_id_cryptocurrencies'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_Cryptocurrencies')
    op.drop_table('trending_cryptocurrencies')
    op.drop_table('user')
    # ### end Alembic commands ###
